Add potential new features and some edit about previous purposals
SPinti-Software/lang-concept pull request #2
Opened 2022-07-03 17:43 UTC by chrapati24

2022-07-03 20:13 UTC, keyboard-slayer reviewed
Interessant concepte !
Je remarque avec ta proposition que le mot clé `then:`  est assez lourd d'utilisation avec les boucles `while/` `for/`. Il faudrait qu'on trouve une solution pour le retirer ou l'améliorer

2022-07-03 20:13 UTC, keyboard-slayer commented on concept1.cpc
> -txt/ "il est ${sys/ /time}"
Comme tu l'as écrit on dirait une variable (et dans certains langage de programmation comme Python, CAPS == constante)

2022-07-03 20:13 UTC, keyboard-slayer commented on concept1.cpc
> +goodby = lambda/ (name) text/ "Goodbye ${name}"
On est déjà discuter de ce changement et on l'a drop :sweat_smile:

2022-07-03 20:13 UTC, keyboard-slayer commented on concept1.cpc
> +include/ "cpcgui"
c'est kiff kiff
je vois pas pourquoi préférer `include` à `use`.

2022-07-03 20:13 UTC, keyboard-slayer commented on concept1.cpc
> +' (Ici Chrapati. Après avoir légèrement modifier quelques trucs qui ont été mis en place par les autres, voici ce que je propose) :
Commentaire inutile on peux voir se que tu propose dans les git blames

2022-07-03 20:13 UTC, keyboard-slayer commented on concept1.cpc
> +let/ /input: "Entrez une valeur : ", x
Tu pointe deux problèmes assez interessant:

* Le manque de user input dans notre design
* Le manque d'assignation de variable dont la valeur est le retour d'une fonction

Ta proposition n'est pas la plus élégante mais Il faudrait qu'on en discute avec les autres :wink:

2022-07-03 20:13 UTC, keyboard-slayer commented on concept1.cpc
> +if/
Pour ce genre de condition je verais une approche comme Python car tu casse un peu le concepte d'opérateur boolean avec ta proposition :thinking:

2022-07-03 20:13 UTC, keyboard-slayer commented on concept1.cpc
> +for/
Même chose que pour le while

2022-07-03 20:13 UTC, keyboard-slayer commented on concept1.cpc
> +    x < y then:
faudrait que les lignes `while/` et `x < 5` soit en une seule ligne et ça serait parfait :ok_hand:

2022-07-04 12:48 UTC, d0p1s4m4 requested changes
J'ai principalement pointé du doigts les propositions que je trouve incohérente et les problèmes qu'elles posent ainsi que donnée mon avis sur des choses ou je suis moins fan. ^^

2022-07-04 12:48 UTC, d0p1s4m4 commented on concept1.cpc
> -txt/ "il est ${sys/ /time}"
Après le CC+ ne prends pas en compte la case. Après je suis pas fan l'idée d'avoir des variables global qui se balade partout.  Après en voir avec les autres la dessus, comment on définis ce genre de variable etc ?

2022-07-04 12:48 UTC, d0p1s4m4 commented on concept1.cpc
> +include/ "cpcgui"
je suis pas fan du mot clef `include` car ça revient a dire "inclus tel fichier dans tel fichier" or ici il serait question de charger des bibliothèques au runtime (compiler .so/.dll) ou des fichiers .cpc donc `use/ ` ou `import` me paraissent plus adapté.

2022-07-04 12:48 UTC, d0p1s4m4 commented on concept1.cpc
> +let/ /input: "Entrez une valeur : ", x
Effectivement on à rien pour les entrées utilisateur. Après pas convaincue par le `/input:` à voir avec les autres

2022-07-04 12:48 UTC, d0p1s4m4 commented on concept1.cpc
> +    or x < y then:
je suis assez opposée a l'utilisation de `or` pour `else if`. Cela casse completement ce genre d'expression:
`if/ x == y or y > z then:`,  `if/` s'écrit de la façon suivante: `if/ expression then:` 

Autre détails important, comme `\n` marque la fin d'une expression comme nous n'utilisons pas de `;` il ne faut pas de saut de ligne entre `if/` et `expression then:`

2022-07-04 12:48 UTC, d0p1s4m4 commented on concept1.cpc
> +    x < y then:
Meme remarque, `\n` marque la fin d'une expression donc ici le code sera évaluée comme:
```c
while ()
{
    x < y then: /* error */
   let x + 1;
}
```

2022-07-04 12:48 UTC, d0p1s4m4 commented on concept1.cpc
> +    let/ x + 1
je ne comprends pas la logique de cette expression. 

ça devrait être pour garder quelques chose de cohérent :
```
let/ x = x + 1
```

2022-07-04 12:48 UTC, d0p1s4m4 commented on concept1.cpc
> +for/
même chose

2022-07-04 12:50 UTC, chrapati24 commented on concept1.cpc
> +goodby = lambda/ (name) text/ "Goodbye ${name}"
Ah bah c'est peut-être une erreur de copier/coller de ma part. Déso x)

2022-07-04 12:53 UTC, keyboard-slayer commented on concept1.cpc
> +    let/ x + 1
Je suis d'accord je l'ai par remarqué :sweat_smile:

2022-07-04 12:53 UTC, keyboard-slayer commented on concept1.cpc
> +let/ /input: "Entrez une valeur : ", x
Pareil à voir :thinking:

2022-07-20 10:41 UTC, d0p1s4m4 requested changes
Il reste encore des points a résoudre (voir les conversation non résolues)

2022-07-20 20:34 UTC, chrapati24 commented on concept1.cpc
> +    or x < y then:
J'ai proposé une solution dans mon nouveau commit. A voir

2022-07-20 20:35 UTC, chrapati24 commented
J'ai update. C'est surtout au niveau des `if/` que j'ai corrigé. Après, pour le reste ce n'est qu'ensemble qu'on peut en débattre. Moi je propose une solution pour les conditions, à vous de voir.

2022-07-21 09:42 UTC, keyboard-slayer commented on concept1.cpc
> +else/
Le problème là c'est lorsque x = y tu auras les deux instructions:

`txt/ "x est egal a y"`
et
`txt/ "x est superieur a y"`

2022-07-21 09:43 UTC, keyboard-slayer commented on concept1.cpc
> +import/ "cpcgui"
Remet `use/` stp

2022-07-21 09:44 UTC, keyboard-slayer commented on concept1.cpc
> +end/
Je crois qu'il faudrait garder les `end/ if` et tous les autres

2022-07-21 09:44 UTC, chrapati24 commented on concept1.cpc
> +end/
A voir. Je vais faire un truc comme ça pour voir ce que ça donne

2022-07-21 09:48 UTC, keyboard-slayer commented on concept1.cpc
> +end/
je pense qu'il aurait fallu attendre l'avis de @d0p1s4m4 pour celui là

j'en suis absoluement pas sur

2022-07-21 12:58 UTC, chrapati24 commented on concept1.cpc
> +end/
Après on peut toujours changer ce qui va pas 🙃

2022-08-23 11:12 UTC, chrapati24 commented
Bon ! J'ai corrigé ce que j'ai pu corrigé. Si il faut retravaillé certaines parties qui ne passeraient certainement pas, merci de me les notifier et de me préciser où il faudrait faire des changements.

2022-08-26 21:29 UTC, d0p1s4m4 requested changes
a part l'histoire du `end/ x` ça m'a l'air assez sympa ^^ et je valide

2022-08-26 21:29 UTC, d0p1s4m4 commented on concept1.cpc
> +' end/ def
perso juste `end/` je trouve aucun interet a `end/ def` , je sais que @keyboard-slayer à proposé la réintroduction, mais je comprends pas pourquoi '^'

2022-08-26 21:29 UTC, d0p1s4m4 commented on concept1.cpc
> +end/ window
comme pour le `end/ def` ^^

2022-08-26 21:33 UTC, keyboard-slayer commented on concept1.cpc
> +' end/ def
en vrais simplement `end/` je trouve ça parfaits

2022-08-26 21:44 UTC, chrapati24 commented
> 

Bah écoute, si c'est bon c'est good alors :p

2022-08-26 21:49 UTC, d0p1s4m4 approved these changes
LGTM

2022-08-26 21:50 UTC, merged